######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 12 00:03:06 2011
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += avector.h
SOURCES += main.cpp
